language: ja

pipeline:
  - name: SpacyNLP
    model: 'ja_ginza'
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: SpacyEntityExtractor
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DucklingEntityExtractor
    url: http://localhost:8000
    dimensions:
      - number
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.9

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100



# language: en

# pipeline:
#   - name: WhitespaceTokenizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#     token_pattern: (?u)\b\w+\b
#   - name: DucklingEntityExtractor
#     url: http://localhost:8000
#     dimensions:
#       - number
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper

# policies:
#   - name: TEDPolicy
#     epochs: 100
#   - name: AugmentedMemoizationPolicy
#   - name: RulePolicy
